export const chapters = [
 {title:'The foundations',description:'Build a clear mental model of Python, one concept at a time.',items:[
 ['Getting started','Install Python and VS Code;Run scripts and use the REPL;Read tracebacks;Understand source code, bytecode and the interpreter'],
 ['Variables & objects','Naming and assignment;Object references and identity;Dynamic typing;is versus ==;Reference counting and garbage collection'],
 ['Built-in data types','int, float, bool and None;Inspect types with type and isinstance;Type conversion;Truthiness;Floating-point precision'],
 ['Operators & expressions','Arithmetic and comparison;Boolean short-circuiting;Membership and identity;Precedence;Assignment expressions'],
 ['Input, output & formatting','input and print;Convert and validate input;f-strings and format specifiers;repr versus str'],
 ['Control flow','if, elif and else;Nested conditions;for and while loops;break, continue and loop else;Structural pattern matching'],
 ]},
 {title:'Working with data',description:'Understand the containers you will use every day.',items:[
 ['Strings','Indexing and slicing;String methods;Immutability;Unicode and encoding;Building strings efficiently'],
 ['Lists','Creation and indexing;Methods and slicing;Mutability and aliasing;Shallow versus deep copies;Dynamic arrays and operation costs'],
 ['Tuples','Packing and unpacking;Single-item tuples;Immutability and mutable members;Named tuples;Choosing tuples versus lists'],
 ['Dictionaries','Keys, values and items;get, setdefault and update;Dictionary comprehensions;Hashability and hash tables;Insertion order'],
 ['Sets','Unique values and membership;Union, intersection and difference;Set comprehensions;frozenset;Hashing and performance'],
 ['Comprehensions','List, set and dictionary comprehensions;Conditions;Nested comprehensions;Generator expressions;Readability trade-offs'],
 ['Collections & copying','Counter and defaultdict;deque and ChainMap;copy and deepcopy;Nested mutable objects;Choosing the right container'],
 ]},
 {title:'Functions & program structure',description:'Write reusable code and learn how Python resolves names.',items:[
 ['Functions','Defining and calling functions;Parameters and return values;Positional and keyword arguments;Default arguments and mutable defaults;args and kwargs;Positional-only and keyword-only parameters;Lambda functions;First-class and higher-order functions'],
 ['Scope & closures','LEGB name resolution;global and nonlocal;Closures;Late binding;Lifetime of local references'],
 ['Recursion','Base cases;Call stack;Recursive problem decomposition;Recursion limits;Iterative alternatives'],
 ['Modules & imports','Create and import modules;Import search path;Module caching;__name__ and entry points;Circular imports'],
 ['Packages & environments','Package structure;Virtual environments;pip;Dependency constraints and lockfiles;pyproject.toml basics'],
 ['Errors & exceptions','Exception hierarchy;try, except, else and finally;raise and exception chaining;Custom exceptions;Avoid broad exception handling'],
 ]},
 {title:'Files & everyday Python',description:'Connect your programs to files, formats, and the outside world.',items:[
 ['Files & paths','pathlib;Text and binary modes;Encodings;Reading large files;Safe writes and resource cleanup'],
 ['Data formats','JSON serialization;CSV reading and writing;datetime and time zones;Parsing and validation;Serialization safety'],
 ['Standard library essentials','itertools;functools;math and statistics;random versus secrets;os, sys and subprocess'],
 ['Regular expressions','Patterns and character classes;Groups and capture;search, match and fullmatch;Substitution;When string methods are better'],
 ['HTTP & APIs','Requests and responses;JSON APIs;Timeouts and retries;Status and error handling;Pagination;API secrets and environment variables'],
 ['Command-line programs','argparse;Exit codes;stdin and stdout;Configuration;Build a reusable CLI'],
 ]},
 {title:'Object-oriented Python',description:'Model behaviour with objects without overcomplicating your code.',items:[
 ['Classes & instances','Class and instance attributes;self and __init__;Instance methods;Object creation with __new__;Composition'],
 ['Inheritance & composition','Inheritance and overriding;super;Method resolution order;Multiple inheritance;Prefer composition when appropriate'],
 ['Properties & descriptors','property;Getters and setters;Descriptor protocol;Attribute lookup;__getattr__ versus __getattribute__'],
 ['The data model','Dunder methods;__repr__ and __str__;Equality and hashing;Operator overloading;Container protocols'],
 ['Dataclasses & structured models','dataclass fields;Defaults and default_factory;Frozen dataclasses;slots;Validation boundaries'],
 ['Class design','Class methods and static methods;Abstract base classes;Protocols;Small cohesive interfaces;Avoid unnecessary inheritance'],
 ]},
 {title:'Advanced language tools',description:'Explore the mechanisms that make Python expressive.',items:[
 ['Iterators & generators','Iterable versus iterator;iter and next;yield and generator state;yield from;Lazy evaluation and exhaustion'],
 ['Decorators','Function wrappers;functools.wraps;Decorators with arguments;Stacking decorators;Practical timing and caching'],
 ['Context managers','with statement;__enter__ and __exit__;contextlib.contextmanager;ExitStack;Exception handling and cleanup'],
 ['Typing','Annotations;Union and Optional;Generics;TypedDict and Protocol;Static type checking;Runtime versus static guarantees'],
 ['Functional patterns','Pure functions;map, filter and reduce;partial;Caching with lru_cache;Sorting with key functions'],
 ['Introspection','dir, vars and getattr;inspect;Callable signatures;Attribute access;When metaprogramming is unnecessary'],
 ]},
 {title:'Writing dependable software',description:'Develop the habits that make code maintainable and trustworthy.',items:[
 ['Readable Python','PEP 8 principles;Meaningful names;Small functions;Docstrings;Formatting and linting;Avoid clever code'],
 ['Testing','pytest basics;Assertions and fixtures;Parameterization;Unit versus integration tests;Mocks at boundaries;Edge cases and regression tests'],
 ['Debugging & logging','Breakpoints and debugger;Traceback analysis;Logging levels and handlers;Reproduce and isolate bugs;Avoid logging secrets'],
 ['Project structure & Git','Separate modules by responsibility;src and tests directories;Git commits and branches;.gitignore;Document setup and usage'],
 ['Packaging & dependencies','pyproject metadata;Build wheels;Dependency groups;Versioning;Editable installs;Reproducible environments'],
 ['Secure & robust code','Validate external input;Avoid eval and unsafe pickle;Manage secrets;Resource limits;Dependency hygiene'],
 ]},
 {title:'Performance & concurrency',description:'Measure first, then choose the right execution model.',items:[
 ['Complexity & profiling','Time and space complexity;timeit;cProfile;Memory profiling;Benchmark representative workloads'],
 ['Memory & runtime internals','Object allocation;Reference counting and cycles;Mutable versus immutable costs;Bytecode with dis;CPython implementation details'],
 ['Threads','Thread lifecycle;Locks and race conditions;ThreadPoolExecutor;I/O-bound work;The GIL and free-threaded builds'],
 ['Processes','ProcessPoolExecutor;CPU-bound work;Serialization overhead;Shared state;Main entry-point guard'],
 ['Async Python','Coroutines and await;Event loop;Tasks and gather;Cancellation and timeouts;Blocking work in async code'],
 ]},
 {title:'The bridge to AI / ML',description:'Bring your Python skills together before moving into the next path.',items:[
 ['Numerical computing foundations','Array thinking;Shapes and dimensions;Vectorization concepts;Numerical precision;Prepare for NumPy'],
 ['Data workflow foundations','Load and validate datasets;Missing and inconsistent values;Separate processing stages;Reproducible randomness;Prepare for pandas'],
 ['Build a Python project','Choose a useful small problem;Break work into modules;Add tests and types;Handle errors and logging;Document and review the project'],
 ]},
];
export const topics=chapters.flatMap((c,chapter)=>c.items.map(([title,subtopics])=>({id:title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,''),title,chapter,subtopics:subtopics.split(';'),objective:`Be able to explain and confidently apply ${title.toLowerCase()}, including the following concepts.`})));
